version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: 'circleci/node'
    steps:
      - checkout
      - run:
          name: Install NVM
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - run:
          name: Node.js 12
          command: nvm install --lts=erbium && npm -g npm && npm run test
      - run:
          name: Node.js 14
          command: nvm install --lts=fermium && npm -g npm && npm run test
      - run:
          name: Node.js 16
          command: nvm install --lts=gallium && npm -g npm && npm run coveralls
      - coveralls/upload
